In [2]:
import numpy as np
low = 0 #incluye el limite inferior
high = 10 # no incluye el límite superior
size = (3, 4) # 3 filas y 4 columnas
random_generator_seed = np.random.default_rng()
two_d_array = random_generator_seed.uniform(low, high, size)
two_d_array

array([[7.74010032, 5.96154817, 6.42584474, 7.24993013],
       [8.78851561, 9.88089875, 3.71487976, 5.08458822],
       [4.55889098, 2.87134606, 4.32370624, 2.21905424]])

In [4]:
# nos quedamos con todas las filas y las columnas 3, 4, 2, y reptimos la 3 (índices 2,3,1,2)
lista_indices_columnas = [2, 3, 1, 2, 0]
two_d_array[:, lista_indices_columnas]

array([[6.42584474, 7.24993013, 5.96154817, 6.42584474, 7.74010032],
       [3.71487976, 5.08458822, 9.88089875, 3.71487976, 8.78851561],
       [4.32370624, 2.21905424, 2.87134606, 4.32370624, 4.55889098]])

In [5]:
a = np.array([0, 1, 2])
b = 5
a + b

array([5, 6, 7])

In [6]:
# linea 2 de la imagen:
a = np.ones((3, 3))
b = np.array([0, 1, 2])
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
b

array([0, 1, 2])

In [9]:
a = np.array([[0], [1], [2]])
print('\na.shape:', a.shape)
print('a:')
print(a)


a.shape: (3, 1)
a:
[[0]
 [1]
 [2]]


In [10]:
b = np.array([0, 1, 2])
print('\nb.shape:', b.shape)
print('b:')
print(b)

print('\na+b:')
a+b


b.shape: (3,)
b:
[0 1 2]

a+b:


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Hands On

# Ejercicio 1

 Dada la instancia de NumPy array

data = np.array([[0, 1, 2, 3, 4], 
              [2, 3, 5, 6, 7], 
              [5, 6, 7, 8, 9], 
              [10, 11, 12, 13, 14], 
              [15, 16, 17, 18, 19], 
              [1, 2, 3, 4, 5]
             ])

Obtener un array que tenga sólo las filas impares de 'data' usando:

Slicing:

Fancy indexing

El resultado debe ser

np.array([[0, 1, 2, 3, 4], 
    [5, 6, 7, 8, 9], 
    [15, 16, 17, 18, 19]])

In [12]:
data = np.array([[0, 1, 2, 3, 4], 
              [2, 3, 5, 6, 7], 
              [5, 6, 7, 8, 9], 
              [10, 11, 12, 13, 14], 
              [15, 16, 17, 18, 19], 
              [1, 2, 3, 4, 5]
             ])

In [13]:
data

array([[ 0,  1,  2,  3,  4],
       [ 2,  3,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 1,  2,  3,  4,  5]])

In [26]:
#Slicing: cuando accedemos a los elementos con los parámetros start,stop,step: my_array[0:5:-1]
data[0:6:2]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [28]:
#Fancy Indexing: Cuando creamos una lista de índices y la usamos para acceder a ciertos elementos del array: my_array[[3,5,7,8]]
# nos quedamos con todas las columnas y las filas 1, 3, 5  (índices 0,2,4)
lista_indices_filas = [0, 2, 4]
data[lista_indices_filas]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [33]:
#Boolean Indexing: Cuando creamos una “máscara booleana” (un array o lista de True y False) para acceder a ciertos elementos: 
#my_array[my_array > 4]
mask_great_15 = data > 15
mask_great_15

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [34]:
data[mask_great_15]

array([16, 17, 18, 19])

# Ejercicio 2

In [37]:
#Seleccionar los elementos de valor par de 'data' usando boolean indexing
#Boolean Indexing: Cuando creamos una “máscara booleana” (un array o lista de True y False) para acceder a ciertos elementos: 
#Realizamos con modulo 2

In [39]:
mask_pares=data%2==0
mask_pares

array([[ True, False,  True, False,  True],
       [ True, False, False,  True, False],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [False,  True, False,  True, False]])

In [40]:
data[mask_pares]

array([ 0,  2,  4,  2,  6,  6,  8, 10, 12, 14, 16, 18,  2,  4])